name: Publish Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # Build RadiantPi.Kaleidescape
      - name: Restore
        run: dotnet restore Source/RadiantPi.Kaleidescape/RadiantPi.Kaleidescape.csproj
      - name: Build
        run: dotnet build --no-restore --configuration Release Source/RadiantPi.Kaleidescape/RadiantPi.Kaleidescape.csproj
      - name: Pack
        run: dotnet pack --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o . Source/RadiantPi.Kaleidescape/RadiantPi.Kaleidescape.csproj

      # Build Samples
      - name: Build Show Events Sample
        run: dotnet build Samples/ShowEvents/ShowEvents.csproj
      - name: Build Show MovieDB User Score Sample
        run: dotnet build Samples/ShowMovieDBUserScore/ShowMovieDBUserScore.csproj

      # Publish RadiantPi.Kaleidescape
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
